<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

use Eduweb2\Libcore\User;
use Eduweb2\Libcore\Leerkracht;

class LeerkrachtSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('leerkracht')->truncate();
        $arr =  array(
            array('voornaam' => 'Nathalie','achternaam' => 'De Keyser','naamcode' => 'NDEK'),
            array('voornaam' => 'Oliver','achternaam' => 'Debeuf','naamcode' => 'ODEB'),
            array('voornaam' => 'Luc','achternaam' => 'Maerevoet','naamcode' => 'LMAE'),
            array('voornaam' => 'Luc','achternaam' => 'Lambert','naamcode' => 'LLAM'),
            array('voornaam' => 'Lieve','achternaam' => 'De Schrijver','naamcode' => 'LDES'),
            array('voornaam' => 'Luc','achternaam' => 'Blommaerts','naamcode' => 'LBLO'),
            array('voornaam' => 'Kristine','achternaam' => 'Waszmann','naamcode' => 'KWAS'),
            array('voornaam' => 'Koen','achternaam' => 'Van Vlaenderen','naamcode' => 'KVVL'),
            array('voornaam' => 'Koen','achternaam' => 'Van Meel','naamcode' => 'KVME'),
            array('voornaam' => 'Kathleen','achternaam' => 'Vastenavont','naamcode' => 'KVAS'),
            array('voornaam' => 'Kris','achternaam' => 'Stordeur','naamcode' => 'KSTO'),
            array('voornaam' => 'Koen','achternaam' => 'Roggemans','naamcode' => 'KROG'),
            array('voornaam' => 'Kathleen','achternaam' => 'Plasqui','naamcode' => 'KPLA'),
            array('voornaam' => 'Kristin','achternaam' => 'Maes','naamcode' => 'KMAE'),
            array('voornaam' => 'Karlijne','achternaam' => 'Hens','naamcode' => 'KHEN'),
            array('voornaam' => 'Koen','achternaam' => 'Bosschaerts','naamcode' => 'KBOS'),
            array('voornaam' => 'Johan','achternaam' => 'Ruyters','naamcode' => 'JRUY'),
            array('voornaam' => 'Jos','achternaam' => 'Herrygers','naamcode' => 'JHER'),
            array('voornaam' => 'Jan','achternaam' => 'Duden','naamcode' => 'JDUD'),
            array('voornaam' => 'Jan','achternaam' => 'Daelemans','naamcode' => 'JDAE'),
            array('voornaam' => 'Jean-Pierre','achternaam' => 'Callewaert','naamcode' => 'JCAL'),
            array('voornaam' => 'Isabelle','achternaam' => 'Verbiest','naamcode' => 'IVER'),
            array('voornaam' => 'Iris','achternaam' => 'Van Duffel','naamcode' => 'IVDU'),
            array('voornaam' => 'Inge','achternaam' => 'Stuer','naamcode' => 'ISTU'),
            array('voornaam' => 'Luc','achternaam' => 'Pierrart','naamcode' => 'LPIE'),
            array('voornaam' => 'Ingrid','achternaam' => 'De Gezelle','naamcode' => 'IDEG'),
            array('voornaam' => 'Inge','achternaam' => 'De Clerck','naamcode' => 'IDEC'),
            array('voornaam' => 'Inge','achternaam' => 'Bulens','naamcode' => 'IBUL'),
            array('voornaam' => 'Ilse','achternaam' => 'Antonissen','naamcode' => 'IANT'),
            array('voornaam' => 'Hilde','achternaam' => 'Willaert','naamcode' => 'HWIL'),
            array('voornaam' => 'Herman','achternaam' => 'Vermeer','naamcode' => 'HVER'),
            array('voornaam' => 'Herman','achternaam' => 'Van den Bergh','naamcode' => 'HVDB'),
            array('voornaam' => 'Hugo','achternaam' => 'Troch','naamcode' => 'HTRO'),
            array('voornaam' => 'Hilde','achternaam' => 'Smeets','naamcode' => 'HSME'),
            array('voornaam' => 'Dries','achternaam' => 'Van Doorn','naamcode' => 'DVDO'),
            array('voornaam' => 'Hans','achternaam' => 'Jacobs','naamcode' => 'HJAC'),
            array('voornaam' => 'Herman','achternaam' => 'Hadermann','naamcode' => 'HHAD'),
            array('voornaam' => 'Ria','achternaam' => 'Lalleman','naamcode' => 'RLAL'),
            array('voornaam' => 'Kristel','achternaam' => 'Scheldeman','naamcode' => 'KSCH'),
            array('voornaam' => 'Griet','achternaam' => 'Verschueren','naamcode' => 'GVER'),
            array('voornaam' => 'Gonda','achternaam' => 'Van Dijck','naamcode' => 'GVDY'),
            array('voornaam' => 'Gert','achternaam' => 'Van den Eynde','naamcode' => 'GVDE'),
            array('voornaam' => 'Greta','achternaam' => 'Jacobs','naamcode' => 'GJAC'),
            array('voornaam' => 'Gerd','achternaam' => 'Cornelissen','naamcode' => 'GCOR'),
            array('voornaam' => 'Liesbet','achternaam' => 'Sonck','naamcode' => 'LSON'),
            array('voornaam' => 'Els','achternaam' => 'Coppens','naamcode' => 'ECOP'),
            array('voornaam' => 'Els','achternaam' => 'Bolsens','naamcode' => 'EBOL'),
            array('voornaam' => 'Danny','achternaam' => 'Van Beneden','naamcode' => 'DVBE'),
            array('voornaam' => 'Dirk','achternaam' => 'Rylant','naamcode' => 'DRYL'),
            array('voornaam' => 'Clark','achternaam' => 'Peeters','naamcode' => 'CPEE'),
            array('voornaam' => 'Christiane','achternaam' => 'Janssens','naamcode' => 'CJAN'),
            array('voornaam' => 'Carlo','achternaam' => 'Heulens','naamcode' => 'CHEU'),
            array('voornaam' => 'Chris','achternaam' => 'Goossenaerts','naamcode' => 'CGOO'),
            array('voornaam' => 'Cindy','achternaam' => 'Broothaers','naamcode' => 'CBRO'),
            array('voornaam' => 'Bart','achternaam' => 'Van Gyseghem','naamcode' => 'BVGY'),
            array('voornaam' => 'Bob','achternaam' => 'Bastiaensen','naamcode' => 'BBAS'),
            array('voornaam' => 'Ariane','achternaam' => 'Timperman','naamcode' => 'ATIM'),
            array('voornaam' => 'Annick','achternaam' => 'Schelfhout','naamcode' => 'ASCH'),
            array('voornaam' => 'Veerle','achternaam' => 'Raats','naamcode' => 'VRAA'),
            array('voornaam' => 'Annick','achternaam' => 'Grupping','naamcode' => 'AGRU'),
            array('voornaam' => 'Anne','achternaam' => 'Groven','naamcode' => 'AGRO'),
            array('voornaam' => 'Ann','achternaam' => 'De Clercq','naamcode' => 'ADEC'),
            array('voornaam' => 'Annemie','achternaam' => 'Creytens','naamcode' => 'ACRE'),
            array('voornaam' => 'Ann','achternaam' => 'Caremans','naamcode' => 'ACAR'),
            array('voornaam' => 'Lut','achternaam' => 'De Prins','naamcode' => 'LDEP'),
            array('voornaam' => 'Tessa','achternaam' => 'Van den Heuvel','naamcode' => 'TVDH'),
            array('voornaam' => 'Ann','achternaam' => 'Antonissen','naamcode' => 'AANT'),
            array('voornaam' => 'Katrien','achternaam' => 'Verschooten','naamcode' => 'KVRS'),
            array('voornaam' => 'Line','achternaam' => 'Van den Broeck','naamcode' => 'LVDB'),
            array('voornaam' => 'Sarah','achternaam' => 'De Jongh','naamcode' => 'SDEJ'),
            array('voornaam' => 'Wendy','achternaam' => 'Van Beylen','naamcode' => 'WVBE'),
            array('voornaam' => 'Hans','achternaam' => 'Peeters','naamcode' => 'HPEE'),
            array('voornaam' => 'Liesbeth','achternaam' => 'Cornelissen','naamcode' => 'LCOR'),
            array('voornaam' => 'Jef','achternaam' => 'Buis','naamcode' => 'EXAM'),
            array('voornaam' => 'Lindy','achternaam' => 'Van Beylen','naamcode' => 'LVBE'),
            array('voornaam' => 'Lotte','achternaam' => 'Gysels','naamcode' => 'LGYS'),
            array('voornaam' => 'Klaartje','achternaam' => 'Van Campen','naamcode' => 'KVCA'),
            array('voornaam' => 'Guy','achternaam' => 'Van Wynsberghe','naamcode' => 'GVWY'),
            array('voornaam' => 'Christoph','achternaam' => 'De Voeght','naamcode' => 'CDEV'),
            array('voornaam' => 'Pieter','achternaam' => 'Serrien','naamcode' => 'PSER'),
            array('voornaam' => 'Anaïs','achternaam' => 'Fayt','naamcode' => 'AFAY'),
            array('voornaam' => 'Dirk','achternaam' => 'Lenart','naamcode' => 'DLEN'),
            array('voornaam' => 'Kathleen','achternaam' => 'Gedopt','naamcode' => 'KGED'),
            array('voornaam' => 'Luc','achternaam' => 'Vercammen','naamcode' => 'LVER'),
            array('voornaam' => 'Lisbet','achternaam' => 'Vos','naamcode' => 'LVOS'),
            array('voornaam' => 'Rozemarijn','achternaam' => 'Maris','naamcode' => 'RMAR'),
            array('voornaam' => 'Mieke','achternaam' => 'De Caluwé','naamcode' => 'MDCA'),
            array('voornaam' => 'Miriam','achternaam' => 'Defever','naamcode' => 'MDEF'),
            array('voornaam' => 'Marleen','achternaam' => 'Verschoren','naamcode' => 'MVRS'),
            array('voornaam' => 'Nancy','achternaam' => 'Verbruggen','naamcode' => 'NVEB'),
            array('voornaam' => 'Ann','achternaam' => 'Toch','naamcode' => 'ATOC'),
            array('voornaam' => 'Hendrik','achternaam' => 'Boey','naamcode' => 'HBOE'),
            array('voornaam' => 'Manuela','achternaam' => 'Schellemans','naamcode' => 'MSCH'),
            array('voornaam' => 'Martine','achternaam' => 'Sterckx','naamcode' => 'MSTE'),
            array('voornaam' => 'Monique','achternaam' => 'Van Beethoven','naamcode' => 'MVBE'),
            array('voornaam' => 'Miriam','achternaam' => 'Vandamme','naamcode' => 'MVDA'),
            array('voornaam' => 'Marleen','achternaam' => 'Verheyen','naamcode' => 'MVER'),
            array('voornaam' => 'Leen','achternaam' => 'Van Linden','naamcode' => 'MVLI'),
            array('voornaam' => 'Marlies','achternaam' => 'Verdoodt','naamcode' => 'MVRD'),
            array('voornaam' => 'Caroline','achternaam' => 'Alaerts','naamcode' => 'CALA'),
            array('voornaam' => 'Stijn','achternaam' => 'Smagghe','naamcode' => 'SSMA'),
            array('voornaam' => 'Paul','achternaam' => 'Geluykens','naamcode' => 'PGEL'),
            array('voornaam' => 'Pascale','achternaam' => 'Leroy','naamcode' => 'PLER'),
            array('voornaam' => 'Rene','achternaam' => 'Poriau','naamcode' => 'RPOR'),
            array('voornaam' => 'Ria','achternaam' => 'Willems','naamcode' => 'RWIL'),
            array('voornaam' => 'Sigrid','achternaam' => 'De Haes','naamcode' => 'SDHA'),
            array('voornaam' => 'Sigrid','achternaam' => 'Op de Beeck','naamcode' => 'SODB'),
            array('voornaam' => 'Steven','achternaam' => 'Walkiers','naamcode' => 'SWAL'),
            array('voornaam' => 'Tania','achternaam' => 'Joris','naamcode' => 'TJOR'),
            array('voornaam' => 'Tom','achternaam' => 'Speleman','naamcode' => 'TSPE'),
            array('voornaam' => 'Veronique','achternaam' => 'De Wit','naamcode' => 'VDWI'),
            array('voornaam' => 'Veerle','achternaam' => 'Pison','naamcode' => 'VPSN'),
            array('voornaam' => 'Walter','achternaam' => 'Rochtus','naamcode' => 'WROC'),
            array('voornaam' => 'Wim','achternaam' => 'Vereecke','naamcode' => 'WVER'),
            array('voornaam' => 'Griet','achternaam' => 'Verelst','naamcode' => 'GVEL'),
            array('voornaam' => 'Bart','achternaam' => 'Van Aelst','naamcode' => 'BVAE'),
            array('voornaam' => 'Anna','achternaam' => 'Roeykens','naamcode' => 'AROE'),
            array('voornaam' => 'Katleen','achternaam' => 'Lierman','naamcode' => 'KLIE'),
            array('voornaam' => 'Hilde','achternaam' => 'Adriaenssens','naamcode' => 'HADR'),
            array('voornaam' => 'Chantal','achternaam' => 'Joris','naamcode' => 'CJOR'),
            array('voornaam' => 'Tom','achternaam' => 'Verheyden','naamcode' => 'TVER'),
            array('voornaam' => 'Liesbeth','achternaam' => 'Bresseleers','naamcode' => 'LBRE'),
            array('voornaam' => 'Wilfried','achternaam' => 'Van Wassenhove','naamcode' => 'WVWA'),
            array('voornaam' => 'Freija','achternaam' => 'Van Dyck','naamcode' => 'FVDY'),
            array('voornaam' => 'Hans','achternaam' => 'Lefever','naamcode' => 'HLEF'),
            array('voornaam' => 'Greet','achternaam' => 'Van Campenhout','naamcode' => 'GVCA'),
            array('voornaam' => 'Kristin','achternaam' => 'Donné','naamcode' => 'KDON'),
            array('voornaam' => 'Kristien','achternaam' => 'Bogaerts','naamcode' => 'KBOG'),
            array('voornaam' => 'Mitte','achternaam' => 'Schroeven','naamcode' => 'MSCR'),
            array('voornaam' => 'Lieve','achternaam' => 'Keppens','naamcode' => 'LKEP'),
            array('voornaam' => 'Veerle','achternaam' => 'Van Caeneghem','naamcode' => 'VVCA'),
            array('voornaam' => 'Katrien','achternaam' => 'Van Bael','naamcode' => 'KVBA'),
            array('voornaam' => 'Kathleen','achternaam' => 'Van Haelst','naamcode' => 'KVHA'),
            array('voornaam' => 'Lieve','achternaam' => 'Vandewijer','naamcode' => 'LVDW'),
            array('voornaam' => 'Gerrit','achternaam' => 'Ceuppens','naamcode' => 'GCEU'),
            array('voornaam' => 'Nele','achternaam' => 'Deklerck','naamcode' => 'NDKL'),
            array('voornaam' => 'Anne','achternaam' => 'De Koning','naamcode' => 'ADEK'),
            array('voornaam' => 'Dries','achternaam' => 'Kets','naamcode' => 'DKET'),
            array('voornaam' => 'Lieke','achternaam' => 'Spithoven','naamcode' => 'LSPI'),
            array('voornaam' => 'An','achternaam' => 'Torfs','naamcode' => 'ATOR'),
            array('voornaam' => 'Tom','achternaam' => 'Van Der Auwera','naamcode' => 'TVDA'),
            array('voornaam' => 'Greet','achternaam' => 'Van Everbroeck','naamcode' => 'GVEV'),
            array('voornaam' => 'Liesbeth','achternaam' => 'Van Geenhoven','naamcode' => 'LVGE'),
            array('voornaam' => 'Ilse','achternaam' => 'Verbruggen','naamcode' => 'IVBR'),
            array('voornaam' => 'Isabelle','achternaam' => 'Fassin','naamcode' => 'IFAS'),
            array('voornaam' => 'Carin','achternaam' => 'Wille','naamcode' => 'CWIL'),
            array('voornaam' => 'Bert','achternaam' => 'Scheers','naamcode' => 'BSCR'),
            array('voornaam' => 'Jelle','achternaam' => 'Simons','naamcode' => 'JSIM'),
            array('voornaam' => 'Nadia','achternaam' => 'Schuermans','naamcode' => 'NSCU'),
            array('voornaam' => 'Annelies','achternaam' => 'Melis','naamcode' => 'AMEL'),
            array('voornaam' => 'Ann','achternaam' => 'Coemans','naamcode' => 'ACOE'),
            array('voornaam' => 'Sabine','achternaam' => 'Vermeulen','naamcode' => 'SVRM'),
            array('voornaam' => 'Jessika','achternaam' => 'De Maeyer','naamcode' => 'JDMA'),
            array('voornaam' => 'Patrick','achternaam' => 'Cools','naamcode' => 'PCOO'),
            array('voornaam' => 'Tania','achternaam' => 'Swinkels','naamcode' => 'TSWI'),
            array('voornaam' => 'Liesbeth','achternaam' => 'Kustermans','naamcode' => 'LKUS'),
            array('voornaam' => 'Nancy','achternaam' => 'Schonenberg','naamcode' => 'NSCH'),
            array('voornaam' => 'Bart','achternaam' => 'Van Gompel','naamcode' => 'BVGO'),
            array('voornaam' => 'Ludo','achternaam' => 'Van Herck','naamcode' => 'LVHE'),
            array('voornaam' => 'Annelies','achternaam' => 'Van Oost','naamcode' => 'AVOO'),
            array('voornaam' => 'Kristel','achternaam' => 'Molkens','naamcode' => 'KMOL'),
            array('voornaam' => 'Eva','achternaam' => 'Begine','naamcode' => 'EBEG'),
            array('voornaam' => 'Carla','achternaam' => 'Spiessens','naamcode' => 'CSPI'),
            array('voornaam' => 'Nisse','achternaam' => 'Van Dessel','naamcode' => 'NVDE'),
            array('voornaam' => 'Thierry','achternaam' => 'Van den Ouwelant','naamcode' => 'TVDO'),
            array('voornaam' => 'Stijn','achternaam' => 'Van Rompaey','naamcode' => 'SVRO'),
            array('voornaam' => 'Caroline','achternaam' => 'Van Landuyt','naamcode' => 'CVLA'),
            array('voornaam' => 'An','achternaam' => 'Lauwrys','naamcode' => 'ALAU'),
            array('voornaam' => 'Kathleen','achternaam' => 'De Mondt','naamcode' => 'KDMO'),
            array('voornaam' => 'Tim','achternaam' => 'Bal','naamcode' => 'TBAL'),
            array('voornaam' => 'Kim','achternaam' => 'Soetewey','naamcode' => 'KSOE'),
            array('voornaam' => 'Sonja','achternaam' => 'Michiels','naamcode' => 'SMIC'),
            array('voornaam' => 'Marina','achternaam' => 'Vervloet','naamcode' => 'MVVL'),
            array('voornaam' => 'Christel','achternaam' => 'Rottiers','naamcode' => 'CROT'),
            array('voornaam' => 'Carina','achternaam' => 'Binnemans','naamcode' => 'CBIN'),
            array('voornaam' => 'Philippe','achternaam' => 'Aerts','naamcode' => 'PAER'),
            array('voornaam' => 'Pol','achternaam' => 'Op de Beeck','naamcode' => 'PODB'),
            array('voornaam' => 'Jurgen','achternaam' => 'Goemans','naamcode' => 'JGOE'),
            array('voornaam' => 'Marijke','achternaam' => 'Van De Ven','naamcode' => 'MVDV'),
            array('voornaam' => 'Kelly','achternaam' => 'Waegeneire','naamcode' => 'KWAE'),
            array('voornaam' => 'Farrah','achternaam' => 'Janssens','naamcode' => 'FJAS'),
            array('voornaam' => 'Loubna','achternaam' => 'Belkhyr','naamcode' => 'LBEL'),
            array('voornaam' => 'Mats','achternaam' => 'Troch','naamcode' => 'MTRO'),
            array('voornaam' => 'Barbara','achternaam' => 'Degroote','naamcode' => 'BDEG'),
            array('voornaam' => 'Elissa','achternaam' => 'Remmery','naamcode' => 'EREM'),
            array('voornaam' => 'Kathleen','achternaam' => 'Vermeire','naamcode' => 'KVRM'),
            array('voornaam' => 'Ann','achternaam' => 'Decorte','naamcode' => 'ADCO'),
            array('voornaam' => 'Ingrid','achternaam' => 'Boon','naamcode' => 'IBOO'),
            array('voornaam' => 'Erik','achternaam' => 'Van Harck','naamcode' => 'EVHA'),
            array('voornaam' => 'Laurence','achternaam' => 'Scheyvaerts','naamcode' => 'LSCH'),
            array('voornaam' => 'Iwan','achternaam' => 'Verelst','naamcode' => 'IVRE'),
            array('voornaam' => 'Tim','achternaam' => 'Van den Bergh','naamcode' => 'TVBE'),
            array('voornaam' => 'Chris','achternaam' => 'Berode','naamcode' => 'CBER'),
            array('voornaam' => 'Marjan','achternaam' => 'Caluwé','naamcode' => 'MCAL'),
            array('voornaam' => 'Kristof','achternaam' => 'Daems','naamcode' => 'KDAE'),
            array('voornaam' => 'Kristien','achternaam' => 'Van Vlerken','naamcode' => 'KVAV'),
            array('voornaam' => 'Jens','achternaam' => 'Van Wolputte','naamcode' => 'JVWO'),
            array('voornaam' => 'Hans','achternaam' => 'Van Nespen','naamcode' => 'HVNE'),
            array('voornaam' => 'Leen','achternaam' => 'Van Doren','naamcode' => 'LVDO'),
            array('voornaam' => 'Sofie','achternaam' => 'Humblet','naamcode' => 'SHUM'),
            array('voornaam' => 'Sofie','achternaam' => 'Brys','naamcode' => 'SBRY'),
            array('voornaam' => 'Marina','achternaam' => 'Van Der Velden','naamcode' => 'ZZMV'),
            array('voornaam' => 'Linde','achternaam' => 'Corte','naamcode' => 'ZZLC'),
            array('voornaam' => 'Caroline','achternaam' => 'Ooms','naamcode' => 'COOM'),
            array('voornaam' => 'Annelies','achternaam' => 'Van Nunen','naamcode' => 'AVNU'),
            array('voornaam' => 'Jeroen','achternaam' => 'Hendrickx','naamcode' => 'JHEN'),
            array('voornaam' => 'Kristine','achternaam' => 'Hadermann','naamcode' => 'KHAD'),
            array('voornaam' => 'William','achternaam' => 'Vercammen','naamcode' => 'WVEC'),
            array('voornaam' => 'Julian','achternaam' => 'Admiraal','naamcode' => 'JADM'),
            array('voornaam' => 'Tristan','achternaam' => 'Van Camp','naamcode' => 'TVCA'),
            array('voornaam' => 'Ruth','achternaam' => 'Plessers','naamcode' => 'RPLE'),
            array('voornaam' => 'Philippe','achternaam' => 'Van Impe','naamcode' => 'PVIM'),
            array('voornaam' => 'Carolien','achternaam' => 'Cuypers','naamcode' => 'CCUY'),
            array('voornaam' => 'Glenda','achternaam' => 'Hauwaerts','naamcode' => 'GHAU'),
            array('voornaam' => 'Marcus','achternaam' => 'Engelen','naamcode' => 'MENG'),
            array('voornaam' => 'Nicolas','achternaam' => 'Charlot','naamcode' => 'NCHA'),
            array('voornaam' => 'Lien','achternaam' => 'Valkenborgh','naamcode' => 'LVAL'),
            array('voornaam' => 'Antoon','achternaam' => 'Van Ishoven','naamcode' => 'AVIS'),
            array('voornaam' => 'Ronny','achternaam' => 'Van Turnhout','naamcode' => 'RVTN'),
            array('voornaam' => 'Stefanie','achternaam' => 'Van Zonhoven','naamcode' => 'SVZO'),
            array('voornaam' => 'Paulien','achternaam' => 'Van den Eynden','naamcode' => 'PVDE'),
            array('voornaam' => 'Thaïsa','achternaam' => 'Kets','naamcode' => 'ZZTK'),
            array('voornaam' => 'Senne','achternaam' => 'Creemers','naamcode' => 'SCRE'),
            array('voornaam' => 'Katrien','achternaam' => 'Bossaerts','naamcode' => 'KBSS'),
            array('voornaam' => 'Lie','achternaam' => 'Goossens','naamcode' => 'LGSS'),
            array('voornaam' => 'Koen','achternaam' => 'Keersmaekers','naamcode' => 'KKEE'),
            array('voornaam' => 'Tanja','achternaam' => 'Romero','naamcode' => 'TROM'),
            array('voornaam' => 'Bjorn','achternaam' => 'Anthierens','naamcode' => 'BANT'),
            array('voornaam' => 'Silke','achternaam' => 'Bautmans','naamcode' => 'SBAU'),
            array('voornaam' => 'Belinda','achternaam' => 'Van den Bempt','naamcode' => 'BVDB'),
            array('voornaam' => 'Joris','achternaam' => 'Van Camp','naamcode' => 'JCAM'),
            array('voornaam' => 'Rob','achternaam' => 'Van Doorslaer','naamcode' => 'RVDO'),
            array('voornaam' => 'Katrien','achternaam' => 'Wolput','naamcode' => 'KWOL'),
            array('voornaam' => 'Nele','achternaam' => 'Timmermans','naamcode' => 'NTIM'),
            array('voornaam' => 'Martine','achternaam' => 'Verswijvel','naamcode' => 'MVSW'),
            array('voornaam' => 'Vanessa','achternaam' => 'Wouters','naamcode' => 'VWOU'),
            array('voornaam' => 'Gina','achternaam' => 'Van Winkel','naamcode' => 'GVWN'),
            array('voornaam' => 'Tinne','achternaam' => 'Jacobs','naamcode' => 'TJAC'),
            array('voornaam' => 'Inge','achternaam' => 'Wille','naamcode' => 'IWIL'),
            array('voornaam' => 'Yasmine','achternaam' => 'Vlemmix','naamcode' => 'ZZYV'),
            array('voornaam' => 'Katleen','achternaam' => 'Van den Abbeele','naamcode' => 'KVDA'),
            array('voornaam' => 'Jolien','achternaam' => 'Hermans','naamcode' => 'JHEM'),
            array('voornaam' => 'Dimitri','achternaam' => 'Vermeulen','naamcode' => 'DVRM'),
            array('voornaam' => 'Chantal','achternaam' => 'Brodie','naamcode' => 'CBRD'),
            array('voornaam' => 'Gwendy','achternaam' => 'Van der Schraelen','naamcode' => 'GVDS'),
            array('voornaam' => 'Maxime','achternaam' => 'Lambreghts','naamcode' => 'MLAM'),
            array('voornaam' => 'Jan','achternaam' => 'Steenhoudt','naamcode' => 'JSTE'),
            array('voornaam' => 'Wouter','achternaam' => 'D\'Hooghe','naamcode' => 'WDHO'),
            array('voornaam' => 'Dominique','achternaam' => 'Roobrouck','naamcode' => 'DROO'),
            array('voornaam' => 'Maarten','achternaam' => 'Cachet','naamcode' => 'MCAC'),
            array('voornaam' => 'Julie','achternaam' => 'Van Oevelen','naamcode' => 'JVOE'),
            array('voornaam' => 'Alicia','achternaam' => 'Van den Bogaert','naamcode' => 'AVDB'),
            array('voornaam' => 'Jan','achternaam' => 'Van Der Moeren','naamcode' => 'JVDM'),
            array('voornaam' => 'Hatice','achternaam' => 'Kozelo','naamcode' => 'HKOZ'),
            array('voornaam' => 'Elise','achternaam' => 'Robeers','naamcode' => 'EROB'),
            array('voornaam' => 'Veronique','achternaam' => 'Van Oosterwyck','naamcode' => 'VVOO'),
            array('voornaam' => 'Ludivine','achternaam' => 'Brzezicha','naamcode' => 'LBRZ'),
            array('voornaam' => 'Anne','achternaam' => 'Stevens','naamcode' => 'ASTV'),
            array('voornaam' => 'Evy','achternaam' => 'Troubleyn','naamcode' => 'ZZET'),
            array('voornaam' => 'Jade','achternaam' => 'Van Etterbeeck','naamcode' => 'JVAE'),
            array('voornaam' => 'Sarah','achternaam' => 'Jacobs','naamcode' => 'ZZSJ'),
            array('voornaam' => 'Kim','achternaam' => 'Knaeps','naamcode' => 'KKNA'),
            array('voornaam' => 'Pascale','achternaam' => 'Bruynseels','naamcode' => 'PBRU'),
            array('voornaam' => 'Zoë','achternaam' => 'Verlinden','naamcode' => 'ZVER'),
            array('voornaam' => 'Arne','achternaam' => 'Mannaerts','naamcode' => 'AMAN'),
            array('voornaam' => 'Eva','achternaam' => 'Van Aert','naamcode' => 'EVAE'),
            array('voornaam' => 'Karijn','achternaam' => 'Kerstens','naamcode' => 'KKER'),
            array('voornaam' => 'Hannelore','achternaam' => 'Van Genechten','naamcode' => 'HVGE'),
            array('voornaam' => 'Lars','achternaam' => 'Vranken','naamcode' => 'LVRA'),
            array('voornaam' => 'Jens','achternaam' => 'Vantomme','naamcode' => 'JVTO'),
            array('voornaam' => 'Sofie','achternaam' => 'Verachtert','naamcode' => 'SVRA'),
            array('voornaam' => 'Eva','achternaam' => 'Phlips','naamcode' => 'ZZEP'),
            array('voornaam' => 'Wouter','achternaam' => 'Leeuws','naamcode' => 'WLEE'),
            array('voornaam' => 'Tim','achternaam' => 'Vandevenne','naamcode' => 'TVDV'),
            array('voornaam' => 'Vincent','achternaam' => 'Snacken','naamcode' => 'ZZVS'),
            array('voornaam' => 'Bram','achternaam' => 'Goudeseune','naamcode' => 'BGOU'),
            array('voornaam' => 'Katrien','achternaam' => 'Dillen','naamcode' => 'KDIL'),
            array('voornaam' => 'Nils','achternaam' => 'Stas','naamcode' => 'NSTA'),
            array('voornaam' => 'Jeroen','achternaam' => 'Smeyers','naamcode' => 'JSME'),
            array('voornaam' => 'Jirka','achternaam' => 'Van Pellecom','naamcode' => 'JPEL'),
            array('voornaam' => 'Michaël','achternaam' => 'Vloeberghs','naamcode' => 'MVLO'),
            array('voornaam' => 'Helena','achternaam' => 'Meuleman','naamcode' => 'HMEU'),
            array('voornaam' => 'Jan','achternaam' => 'Claes','naamcode' => 'JCLA'),
            array('voornaam' => 'Elke','achternaam' => 'Van Oosten','naamcode' => 'ZZEV'),
            array('voornaam' => 'India','achternaam' => 'Hellemans','naamcode' => 'ZZIH'),
            array('voornaam' => 'Raf','achternaam' => 'Vissers','naamcode' => 'RVIS')
        );
        $leerkrachten = factory(Leerkracht::class, count($arr))->create();
        $users = User::all();
        for ($i = 0; $i < count($leerkrachten);++$i) {
            for ($j = 0;$j<count($users);++$j) {
                if ($arr[$i]["voornaam"]==$users[$j]["voornaam"] && $arr[$i]["achternaam"]==$users[$j]["achternaam"]) {
                    $leerkrachten[$i]["user_id"]=$users[$j]["id"];
                    $leerkrachten[$i]["code"]=$arr[$i]["naamcode"];
                    break;
                }
            }
            $leerkrachten[$i]->save();
        }
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
        Model::reguard();
    }
}
